global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    environment: 'dev'
    cluster: 'jobpulse-dev'

rule_files:
  - "alerts/dev-alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  - job_name: 'auth-service-dev'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'auth-service-dev'
      - target_label: environment
        replacement: 'dev'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(http_server_requests_seconds.*|jvm_.*|auth_.*|hikaricp_.*)$'
        action: keep

  - job_name: 'job-service-dev'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'job-service-dev'
      - target_label: environment
        replacement: 'dev'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(http_server_requests_seconds.*|jvm_.*|job_.*|hikaricp_.*)$'
        action: keep

  # Development-specific exporters
  - job_name: 'postgres-exporter-dev'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s
    relabel_configs:
      - target_label: environment
        replacement: 'dev'

  - job_name: 'kafka-exporter-dev'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s
    relabel_configs:
      - target_label: environment
        replacement: 'dev'
