version: '3.8'

services:
  auth-service:
    volumes:
      - ./:/workspace
      - gradle-cache:/workspace/.gradle
    working_dir: /workspace
    entrypoint: []
    command: ./gradlew :auth-service:bootRun --continuous
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=authuser
      - SPRING_DATASOURCE_PASSWORD=authpass
      - GRADLE_USER_HOME=/workspace/.gradle
      - JWT_SECRET=your-dev-secret-your-dev-secret-your-dev-secret-your-dev-secret
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_EXPIRATION_MS=3600000
      - REFRESH_EXPIRATION_MS=604800000
    depends_on:
      - auth-db
      - kafka

  job-service:
    volumes:
      - ./:/workspace
      - gradle-cache-job:/workspace/.gradle
    working_dir: /workspace
    entrypoint: []
    command: ./gradlew :job-service:bootRun --continuous
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://job-db:5432/jobdb
      - SPRING_DATASOURCE_USERNAME=jobuser
      - SPRING_DATASOURCE_PASSWORD=jobpass
      - GRADLE_USER_HOME=/workspace/.gradle
      - JWT_SECRET=your-dev-secret-your-dev-secret-your-dev-secret-your-dev-secret
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=job-service-group
      - USER_EVENTS_TOPIC=user.events
    depends_on:
      - job-db
      - kafka

volumes:
  gradle-cache:
  gradle-cache-job: