version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=authuser
      - SPRING_DATASOURCE_PASSWORD=authpass
      - JWT_SECRET=your-dev-secret-your-dev-secret-your-dev-secret-your-dev-secret
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - JWT_EXPIRATION_MS=3600000
      - REFRESH_EXPIRATION_MS=604800000
      # OpenAPI Configuration for Development
      - OPENAPI_DEV_URL=http://localhost:8080
      - OPENAPI_PROD_URL=
      - OPENAPI_TITLE=JobPulse Auth Service API (Development)
      - OPENAPI_VERSION=1.0.0
      - OPENAPI_DESCRIPTION=Authentication service for development environment
    depends_on:
      - auth-db
      - kafka
    ports:
      - "8080:8080"
    restart: on-failure

  jobcreationlisting:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: jobcreationlisting
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://job-db:5432/jobdb
      - SPRING_DATASOURCE_USERNAME=jobuser
      - SPRING_DATASOURCE_PASSWORD=jobpass
      - JWT_SECRET=your-dev-secret-your-dev-secret-your-dev-secret-your-dev-secret
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=jobcreationlisting-group
      - USER_EVENTS_TOPIC=user.events
      # OpenAPI Configuration for Development
      - OPENAPI_DEV_URL=http://localhost:8081
      - OPENAPI_PROD_URL=
      - OPENAPI_TITLE=JobPulse Job Service API (Development)
      - OPENAPI_VERSION=1.0.0
      - OPENAPI_DESCRIPTION=Job management service for development environment
    depends_on:
      - job-db
      - kafka
    ports:
      - "8081:8080"
    restart: on-failure