version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  job-db:
    image: postgres:16
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: ${JOB_DB_PASSWORD}
    volumes:
      - job-db-data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - REFRESH_EXPIRATION_MS=${REFRESH_EXPIRATION_MS}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=authuser
      - SPRING_DATASOURCE_PASSWORD=${AUTH_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - auth-db
      - kafka
    ports:
      - "8080:8080"

  job-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: job-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://job-db:5432/jobdb
      - SPRING_DATASOURCE_USERNAME=jobuser
      - SPRING_DATASOURCE_PASSWORD=${JOB_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=job-service-group
      - USER_EVENTS_TOPIC=user.events
    depends_on:
      - job-db
      - kafka
    ports:
      - "8081:8080"

volumes:
  auth-db-data:
  job-db-data: