services:
  auth-service:
    volumes:
      - ./auth-service:/app
      - gradle-cache:/home/gradle/.gradle
    working_dir: /app
    entrypoint: []
    command: ./gradlew bootRun --continuous
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=authuser
      - SPRING_DATASOURCE_PASSWORD=authpass
volumes:
  gradle-cache: