@startuml job-service-architecture
!theme plain
skinparam class {
    BackgroundColor LightGreen
    BorderColor Black
    ArrowColor Black
}

title JobPulse Job Service Architecture

package JobServicePackage {
    !include job-creation-listing/design.puml
    !include job-poster/design.puml
    !include job-seeker/design.puml
}
note top of JobServicePackage
  The JobServicePackage currently hosts the following modules:
    - job-creation-listing: handles job creation and listings
    - job-poster: manages job posts and reviews applications
    - job-seeker: manages applications
  Each module is independent, relies only on contracts, and can be deployed as a separate microservice for scalability.
end note
@enduml