package "com.jobpulse.jobseeker" {
    package controller {
        class JobApplicantController {
        }
    }
    package dto {
        package request {
            class JobPostsRequest
            class JobPostApplicationsRequest
            class UpdateAppliedJobStatusRequest
            class ApplyToJobRequest
        }
        package response {
            class ServiceResult<T> {
                -success: boolean
                -data: T
                -errorMessage: String
                -errorCode: String
                +{static} success(T): ServiceResult<T>
                +{static} failure(String, String): ServiceResult<T>
                +isSuccess(): boolean
                +isFailure(): boolean
            }
            class JobPostsResponse
            class JobPostApplicationsResponse
            class UpdateAppliedJobStatusResponse
            class ApplyToJobResponse
        }
    }
    package event {
        class AppliedJobApplicationStausUpdateEvent {
            +jobPostId: UUID
            +jobApplicantionId: UUID
            +jobApplicantId: UUID
            +updatedById: UUID
        }
        class AppliedJobApplicationDocumentUpdatedEvent {
            +jobPostId: UUID
            +jobApplicantionId: UUID
            +jobApplicantId: UUID
            +jobApplicationFileId: UUID
            +updatedById: UUID
        }
        class JobApplicantSentEvent {
            +jobApplicationId: UUID
            +jobPostId: UUID
            +jobApplicantId: UUID
            +createdAt: LocalDateTime
            +updatedById: UUID
        }
    }
    package repository {
        interface JobApplicantRepository 
    }
    package service {
        interface JobApplicantContract {
            +applyJob(request: ApplyToJobRequest): ServiceResult<ApplyToJobResponse>
            +getAppliedJobs(request: GetAppliedJobsRequest): ServiceResult<AppliedJobsResponse>
            +editAppliedJobDocument(request: EditAppliedJobDocumentRequest): ServiceResult<EditAppliedJobDocumentResponse>
            +updateAppliedJobStatus(request: UpdateAppliedJobStatusRequest): ServiceResult<UpdateAppliedJobStatusResponse>
        }
        class JobApplicantService implements JobApplicantContract {
        }
    }
    JobApplicantController --> JobApplicantContract
    JobApplicantContract <|.. JobApplicantService
    JobApplicantService --> JobApplicantRepository
}